# Generated by Django 4.2.5 on 2023-09-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('file', models.FileField(upload_to='uploads')),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
