# Generated by Django 4.2.5 on 2023-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
