# Generated by Django 4.2.5 on 2023-10-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_lectureview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='views',
        ),
    ]
